### missing package check
if (!requireNamespace("data.table")) install.packages("data.table", type = "source", repos = "https://Rdatatable.gitlab.io/data.table")
if (!requireNamespace("DT")) install.packages("DT", quiet = T)
if (!requireNamespace("ggplot2")) install.packages("ggplot2", quiet = T)
if (!requireNamespace("dplyr")) install.packages("dplyr", quiet = T)
if (!requireNamespace("gganimate")) install.packages("gganimate", quiet = T)
if (!requireNamespace("gifski")) install.packages("gifski", quiet = T)
if (!requireNamespace("knitr")) install.packages("knitr", quiet = T)
if (!requireNamespace("kableExtra")) install.packages("kableExtra", quiet = T)
if (!requireNamespace("shiny")) install.packages("shiny", quiet = T)
if (!requireNamespace("reticulate")) install.packages("reticulate", quiet = T)
if (!requireNamespace("jsonlite")) install.packages("jsonlite", quiet = T)
if (!requireNamespace("magrittr")) install.packages("magrittr", quiet = T)
if (!requireNamespace("tidyverse")) install.packages("tidyverse", quiet = T)
if (!requireNamespace("ggthemes")) install.packages("ggthemes", quiet = T)
if (!requireNamespace("xgboost")) install.packages("xgboost", quiet = T)
if (!requireNamespace("ligthgbm")) install.packages("ligthgbm", quiet = T)
if (!requireNamespace("hrbrthemes")) install.packages("hrbrthemes", repos = c("https://cinc.rud.is", "https://cloud.r-project.org/"), quiet = T)